# Media Toolkit Configuration
# This file contains all presets and settings for audio and video transcoding

audio:
  # Size reduction ratio threshold - keep re-encode only if ≥ 5% smaller
  size_keep_ratio: 0.95
  
  # Quality analysis settings (user configurable)
  quality_thresholds:
    small_folder_files: 3        # Files ≤ this = analyze all
    medium_folder_files: 20      # Files ≤ this = skip first/last
    min_saving_percent: 5        # Don't convert if savings < this %
    
  # SNR sampling configuration
  sampling:
    edge_skip_percent: 10        # Skip this % from folder edges
    min_sample_count: 5          # Minimum samples in large folders
    sample_percentage: 0.2       # Sample this % of files (20%)
    
  # Codec quality estimates (user can adjust based on preferences)
  codec_snr_estimates:
    mp3:
      high_quality_bitrate: 320000
      good_quality_bitrate: 192000
      standard_quality_bitrate: 128000
      high_snr: 85.0
      good_snr: 75.0
      standard_snr: 65.0
      low_snr: 55.0
    aac:
      high_quality_bitrate: 256000
      good_quality_bitrate: 128000
      standard_quality_bitrate: 96000
      high_snr: 80.0
      good_snr: 70.0
      standard_snr: 60.0
      low_snr: 50.0
    opus:
      high_quality_bitrate: 192000
      good_quality_bitrate: 128000
      standard_quality_bitrate: 96000
      high_snr: 85.0
      good_snr: 75.0
      standard_snr: 65.0
      low_snr: 55.0
  
  # Supported audio file extensions
  extensions:
    - .flac
    - .mp3
    - .wav
    - .aac
    - .m4a
    - .ogg
    - .opus
    - .wma
    - .aax

  # Audio encoding presets
  presets:
    music:
      bitrate: "128k"
      application: "audio"
      cutoff: null
      channels: null
      description: "Standard music quality"
      min_snr_db: 70.0               # Minimum SNR for full bitrate
      snr_bitrate_scale: true        # Enable SNR scaling
    
    audiobook:
      bitrate: "64k"
      application: "voip"     # Optimized for speech
      cutoff: null           # No frequency cutoff - preserve full range
      channels: "1"          # Mono for most audiobooks
      description: "High quality mono audiobooks"
      min_snr_db: 50.0       # Lower threshold for voice content
      snr_bitrate_scale: true
    
    audiobook_stereo:
      bitrate: "96k"          # Better quality for stereo (upgraded from 48k)
      application: "voip"
      cutoff: null           # No frequency cutoff - preserve full range
      channels: null         # Keep original channels
      description: "High quality stereo audiobooks"
      min_snr_db: 50.0       # Lower threshold for voice content
      snr_bitrate_scale: true
    
    high:
      bitrate: "192k"
      application: "audio"
      cutoff: null
      channels: null
      description: "High quality music"
      min_snr_db: 75.0       # Higher threshold for high quality
      snr_bitrate_scale: true
    
    low:
      bitrate: "96k"
      application: "audio"
      cutoff: null
      channels: null
      description: "Lower quality for space saving"
      min_snr_db: 60.0       # Moderate threshold for low quality preset
      snr_bitrate_scale: true

video:
  # Video processing settings
  min_savings_percent: 10  # Minimum savings percentage required to keep transcoded file
  size_keep_ratio: 0.95    # Keep transcoded file if new size < (original * ratio)
  
  # Supported video file extensions
  extensions:
    - .mp4
    - .mkv
    - .avi
    - .mov
    - .wmv
    - .flv
    - .webm
    - .m4v

  # Video encoding presets
  presets:
    # === CPU PRESETS (H.264) ===
    default:
      crf: 24
      codec: "libx264"
      preset: "medium"
      description: "Balanced quality and encoding speed"
    
    hq:
      crf: 18
      codec: "libx264"
      preset: "slow"
      description: "High quality, slower encoding"
    
    ultra:
      crf: 15
      codec: "libx264"
      preset: "veryslow"
      description: "Maximum quality, very slow encoding"
    
    fast:
      crf: 26
      codec: "libx264"
      preset: "fast"
      description: "Faster encoding, slightly lower quality"
    
    vfast:
      crf: 28
      codec: "libx264"
      preset: "ultrafast"
      description: "Fastest CPU encoding, lower quality"
    
    # === CPU PRESETS (H.265/HEVC) ===
    h265:
      crf: 24
      codec: "libx265"
      preset: "medium"
      description: "H.265 balanced quality (smaller files)"
    
    h265_hq:
      crf: 18
      codec: "libx265"
      preset: "slow"
      description: "H.265 high quality (very small files)"
    
    h265_ultra:
      crf: 15
      codec: "libx265"
      preset: "veryslow"
      description: "H.265 maximum quality (smallest files)"
    
    h265_fast:
      crf: 26
      codec: "libx265"
      preset: "fast"
      description: "H.265 fast encoding"
    
    # === NVIDIA GPU PRESETS (H.264) ===
    gpu:
      crf: 28  # Higher CRF for GPU encoders
      codec: "h264_nvenc"
      preset: "medium"
      rate_control: "constqp"
      quality_param: "qp"  # Use -qp instead of -crf for NVENC
      description: "GPU-accelerated H.264 encoding"
    
    gpu_hq:
      crf: 24
      codec: "h264_nvenc"
      preset: "slow"
      rate_control: "constqp"
      quality_param: "qp"
      description: "High quality GPU H.264 encoding"
    
    gpu_fast:
      crf: 30
      codec: "h264_nvenc"
      preset: "fast"
      rate_control: "constqp"
      quality_param: "qp"
      description: "Fast GPU H.264 encoding"
    
    gpu_vfast:
      crf: 32
      codec: "h264_nvenc"
      preset: "fast"
      rate_control: "constqp"
      quality_param: "qp"
      description: "Ultra fast GPU H.264 encoding"
    
    # === NVIDIA GPU PRESETS (H.265/HEVC) ===
    gpu_h265:
      crf: 26  # Balanced CRF for GPU encoders
      codec: "hevc_nvenc"
      preset: "medium"
      rate_control: "constqp"
      quality_param: "qp"  # Use -qp instead of -crf for NVENC
      description: "GPU-accelerated H.265 encoding"
    
    gpu_h265_hq:
      crf: 24
      codec: "hevc_nvenc"
      preset: "slow"
      rate_control: "constqp"
      quality_param: "qp"
      description: "High quality GPU H.265 encoding"
    
    gpu_h265_f:
      crf: 30
      codec: "hevc_nvenc"
      preset: "fast"
      rate_control: "constqp"
      quality_param: "qp"
      description: "Fast GPU H.265 encoding"
    
    # === AMD GPU PRESETS (H.264) ===
    amd:
      crf: 28
      codec: "h264_amf"
      preset: "medium"
      quality_param: "qp"  # AMD AMF uses -qp
      description: "AMD GPU-accelerated H.264 encoding"
    
    amd_hq:
      crf: 24
      codec: "h264_amf"
      preset: "slow"
      quality_param: "qp"
      description: "High quality AMD GPU H.264 encoding"
    
    amd_fast:
      crf: 30
      codec: "h264_amf"
      preset: "fast"
      quality_param: "qp"
      description: "Fast AMD GPU H.264 encoding"
    
    # === AMD GPU PRESETS (H.265/HEVC) ===
    amd_h265:
      crf: 28
      codec: "hevc_amf"
      preset: "medium"
      quality_param: "qp"  # AMD AMF uses -qp
      description: "AMD GPU-accelerated H.265 encoding"
    
    amd_h265_hq:
      crf: 24
      codec: "hevc_amf"
      preset: "slow"
      quality_param: "qp"
      description: "High quality AMD GPU H.265 encoding"
    
    # === INTEL GPU PRESETS (QuickSync) ===
    intel:
      crf: 28
      codec: "h264_qsv"
      preset: "medium"
      quality_param: "global_quality"  # Intel QSV uses -global_quality
      description: "Intel QuickSync H.264 encoding"
    
    intel_h265:
      crf: 28
      codec: "hevc_qsv"
      preset: "medium"
      quality_param: "global_quality"  # Intel QSV uses -global_quality
      description: "Intel QuickSync H.265 encoding"
    
    # === SPECIAL PURPOSE PRESETS ===
    archive:
      crf: 15
      codec: "libx265"
      preset: "veryslow"
      description: "Archival quality (maximum compression)"
    
    stream:
      crf: 23
      codec: "libx264"
      preset: "fast"
      description: "Optimized for streaming/web delivery"
    
    mobile:
      crf: 26
      codec: "libx264"
      preset: "fast"
      description: "Optimized for mobile devices"

# Global settings
global:
  # Default number of worker threads (null = auto-detect with thermal-safe limits)
  # Auto-detection uses psutil to monitor system load and temperature,
  # ensuring we don't use too many cores that could cause thermal issues
  # For thermal safety, auto-detection caps at 4 workers and uses half the physical cores
  default_workers: null
  
  # Logging levels: DEBUG, INFO, WARNING, ERROR
  log_level: "INFO"
  
  # Create backup files before replacing originals
  create_backups: true
  
  # Remove backup files after successful conversion
  # Options: "never", "on_success"
  cleanup_backups: "on_success"
