[project]
name = "transcode-toolkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "ninja>=1.11.1.4",
    "nuitka>=2.7.7",
    "numpy>=2.3.0",
    "opencv-python-headless>=4.11.0.86",
    "pydantic>=2.10.0",
    "pydantic-settings>=2.8.0",
    "pyyaml>=6.0.0",
    "ruff>=0.11.13",
    "zstandard>=0.23.0",
]

[dependency-groups]
dev = [
    "mypy>=1.16.0",
    "pytest>=8.4.0",
    "ruff>=0.11.13",
    "ty>=0.0.1a11",
    "types-pyyaml>=6.0.12.20250516",
]
